// Chapter22IncrementerDecrementer (c) Charles Petzold, 2024

let Chapter22IncrementerDecrementer = 
{
    name: "Chapter22IncrementerDecrementer",
    transform: { x: 100, y: 350, scale: 1, rotate: 0 },
    wireCurveRadius: 5,
    nodeRadius: 3,
    propagationDelay: 50,
    components:
    [
        { name:"bit0", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 950},
        { name:"bit1", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 890},
        { name:"bit2", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 830},
        { name:"bit3", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 770},
        { name:"bit4", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 710},
        { name:"bit5", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 650},
        { name:"bit6", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 590},
        { name:"bit7", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 530},
        { name:"bit8", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 470},
        { name:"bit9", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 410},
        { name:"bitA", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 350},
        { name:"bitB", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 290},
        { name:"bitC", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 230},
        { name:"bitD", type: "External", file: "Chapter22IncrementerDecrementerBit", scale: 1.2, x: 170},
        { name:"bitE", type: "External", file: "Chapter22IncrementerDecrementerBitE", scale: 1.2, x: 110},
        { name:"bitF", type: "External", file: "Chapter22IncrementerDecrementerBitF", scale: 1.2, x: 50},

        { name:"latch", type: "Latch", outputs: 16, text: "16-Bit Latch", width: 1000, height: 100, y: -100,
            ports: [{text: "Input", x: 0.5, y: 0},
                    {text: "Clock", x: 0, y: 0.5},
                    {text: "O\u2081\u2085", x: 0.05, y: 1}, 
                    {text: "O\u2081\u2084", x: 0.11, y: 1}, 
                    {text: "O\u2081\u2083", x: 0.17, y: 1}, 
                    {text: "O\u2081\u2082", x: 0.23, y: 1}, 
                    {text: "O\u2081\u2081", x: 0.29, y: 1}, 
                    {text: "O\u2081\u2080", x: 0.35, y: 1}, 
                    {text: "O\u2089", x: 0.41, y: 1}, 
                    {text: "O\u2088", x: 0.47, y: 1}, 
                    {text: "O\u2087", x: 0.53, y: 1}, 
                    {text: "O\u2086", x: 0.59, y: 1}, 
                    {text: "O\u2085", x: 0.65, y: 1}, 
                    {text: "O\u2084", x: 0.71, y: 1}, 
                    {text: "O\u2083", x: 0.77, y: 1}, 
                    {text: "O\u2082", x: 0.83, y: 1}, 
                    {text: "O\u2081", x: 0.89, y: 1}, 
                    {text: "O\u2080", x: 0.95, y: 1}       
                ]},

        { name:"inValue", type: "WordSpinner", value: 0x26AE, y: -150, relative: {xy: { name:"latch", io: "Input"}}},

        { name:"clkButton", type: "MomentaryButton", x: -50, relative: {x: { name:"latch", io: "Clock"}, y: { name:"inValue"}}},
        { name:"clock", type: "Label", text: "Clock", y: -25, relative: {xy: { name:"clkButton", io: "top"}}},
        { name:"clkJoint", type: "Joint", relative: {x: { name:"clkButton"}, y: { name:"latch", io: "Clock"}}},

        { name:"tri", type: "OrigTriStateBuffer", text: "Tri-State Buffer", group:"a", "width": 1000, "height": 100, x: 5, y: 174,
            ports: [{text: "Output", x: 0.5, y: 1},
                    {text: "Enable", x: 1, y: 0.5},
                    {text: "I\u2081\u2085", x: 0.05, y: 0}, 
                    {text: "I\u2081\u2084", x: 0.11, y: 0}, 
                    {text: "I\u2081\u2083", x: 0.17, y: 0}, 
                    {text: "I\u2081\u2082", x: 0.23, y: 0}, 
                    {text: "I\u2081\u2081", x: 0.29, y: 0}, 
                    {text: "I\u2081\u2080", x: 0.35, y: 0}, 
                    {text: "I\u2089", x: 0.41, y: 0}, 
                    {text: "I\u2088", x: 0.47, y: 0}, 
                    {text: "I\u2087", x: 0.53, y: 0}, 
                    {text: "I\u2086", x: 0.59, y: 0}, 
                    {text: "I\u2085", x: 0.65, y: 0}, 
                    {text: "I\u2084", x: 0.71, y: 0}, 
                    {text: "I\u2083", x: 0.77, y: 0}, 
                    {text: "I\u2082", x: 0.83, y: 0}, 
                    {text: "I\u2081", x: 0.89, y: 0}, 
                    {text: "I\u2080", x: 0.95, y: 0}       
                ]},

        { name:"enableOr", type: "OrGate", scale: 0.25, rotate: 180, x: 50, relative: {xy: { name:"tri", io: "Enable"}}},
        { name:"decNode", type: "Node", x: 25, relative: {x: { name:"enableOr", io: "B"}, y: { name:"bit0.incdecNode"}}},
        { name:"decButton", type: "MomentaryButton", relative: {x: { name:"decNode"}, y: { name:"inValue"}}},
        { name:"incButton", type: "MomentaryButton", x: 150, relative: {xy: { name:"decButton"}}},
        { name:"decrement", type: "Label", text: "Decrement", y: -50, relative: {xy: { name:"decButton", io: "top"}}},
        { name:"increment", type: "Label", text: "Increment", y: -50, relative: {xy: { name:"incButton", io: "top"}}},
        { name:"decJoint", type: "Joint", relative: {x: { name:"decButton"}, y: { name:"enableOr", io: "B"}}},
        { name:"incJoint", type: "Joint", relative: {x: { name:"incButton"}, y: { name:"enableOr", io: "A"}}},
        { name:"v", type: "VPropagator", x: 25, y: -25, relative: {xy: { name:"bit0.cascadeNode"}}},
        { name:"vJoint", type: "Joint", relative: {x: { name:"v"}, y: { name:"bit0.cascadeNode"}}},
        { name:"outLight", type: "WordLight", y: 100, relative: {xy: { name:"tri", io: "Output"}}},
        { name:"output", type: "Label", text: "Output", y: 50, relative: {xy: { name:"outLight"}}},


    ],
    wires:
    [
        { points:[{ name:"latch", io: "O\u2080", output: 0}, { name:"bit0.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2081", output: 1}, { name:"bit1.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2082", output: 2}, { name:"bit2.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2083", output: 3}, { name:"bit3.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2084", output: 4}, { name:"bit4.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2085", output: 5}, { name:"bit5.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2086", output: 6}, { name:"bit6.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2087", output: 7}, { name:"bit7.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2088", output: 8}, { name:"bit8.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2089", output: 9}, { name:"bit9.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2081\u2080", output: 10}, { name:"bitA.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2081\u2081", output: 11}, { name:"bitB.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2081\u2082", output: 12}, { name:"bitC.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2081\u2083", output: 13}, { name:"bitD.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2081\u2084", output: 14}, { name:"bitE.inputNode"}]},
        { points:[{ name:"latch", io: "O\u2081\u2085", output: 15}, { name:"bitF.xor1", io: "B", input: 1}]},

        { points:[{ name:"v"}, { name:"vJoint"}, { name:"bit0.cascadeNode"}]},
        { points:[{ name:"bit0.and", io: "out"}, { name:"bit0.loop1"}, { name:"bit0.loop2"}, { name:"bit0.loop3"}, { name:"bit1.cascadeNode"}]},
        { points:[{ name:"bit1.and", io: "out"}, { name:"bit1.loop1"}, { name:"bit1.loop2"}, { name:"bit1.loop3"}, { name:"bit2.cascadeNode"}]},
        { points:[{ name:"bit2.and", io: "out"}, { name:"bit2.loop1"}, { name:"bit2.loop2"}, { name:"bit2.loop3"}, { name:"bit3.cascadeNode"}]},
        { points:[{ name:"bit3.and", io: "out"}, { name:"bit3.loop1"}, { name:"bit3.loop2"}, { name:"bit3.loop3"}, { name:"bit4.cascadeNode"}]},
        { points:[{ name:"bit4.and", io: "out"}, { name:"bit4.loop1"}, { name:"bit4.loop2"}, { name:"bit4.loop3"}, { name:"bit5.cascadeNode"}]},
        { points:[{ name:"bit5.and", io: "out"}, { name:"bit5.loop1"}, { name:"bit5.loop2"}, { name:"bit5.loop3"}, { name:"bit6.cascadeNode"}]},
        { points:[{ name:"bit6.and", io: "out"}, { name:"bit6.loop1"}, { name:"bit6.loop2"}, { name:"bit6.loop3"}, { name:"bit7.cascadeNode"}]},
        { points:[{ name:"bit7.and", io: "out"}, { name:"bit7.loop1"}, { name:"bit7.loop2"}, { name:"bit7.loop3"}, { name:"bit8.cascadeNode"}]},
        { points:[{ name:"bit8.and", io: "out"}, { name:"bit8.loop1"}, { name:"bit8.loop2"}, { name:"bit8.loop3"}, { name:"bit9.cascadeNode"}]},
        { points:[{ name:"bit9.and", io: "out"}, { name:"bit9.loop1"}, { name:"bit9.loop2"}, { name:"bit9.loop3"}, { name:"bitA.cascadeNode"}]},
        { points:[{ name:"bitA.and", io: "out"}, { name:"bitA.loop1"}, { name:"bitA.loop2"}, { name:"bitA.loop3"}, { name:"bitB.cascadeNode"}]},
        { points:[{ name:"bitB.and", io: "out"}, { name:"bitB.loop1"}, { name:"bitB.loop2"}, { name:"bitB.loop3"}, { name:"bitC.cascadeNode"}]},
        { points:[{ name:"bitC.and", io: "out"}, { name:"bitC.loop1"}, { name:"bitC.loop2"}, { name:"bitC.loop3"}, { name:"bitD.cascadeNode"}]},
        { points:[{ name:"bitD.and", io: "out"}, { name:"bitD.loop1"}, { name:"bitD.loop2"}, { name:"bitD.loop3"}, { name:"bitE.cascadeNode"}]},
        { points:[{ name:"bitE.and", io: "out"}, { name:"bitE.loop1"}, { name:"bitE.loop2"}, { name:"bitE.loop3"}, { name:"bitF.cascadeJoint"}, { name:"bitF.xor1", io: "A", input: 0}]},

        { points:[{ name:"decNode"}, { name:"bit0.incdecNode"}]},
        { points:[{ name:"bit0.incdecNode"}, { name:"bit1.incdecNode"}]},
        { points:[{ name:"bit1.incdecNode"}, { name:"bit2.incdecNode"}]},
        { points:[{ name:"bit2.incdecNode"}, { name:"bit3.incdecNode"}]},
        { points:[{ name:"bit3.incdecNode"}, { name:"bit4.incdecNode"}]},
        { points:[{ name:"bit4.incdecNode"}, { name:"bit5.incdecNode"}]},
        { points:[{ name:"bit5.incdecNode"}, { name:"bit6.incdecNode"}]},
        { points:[{ name:"bit6.incdecNode"}, { name:"bit7.incdecNode"}]},
        { points:[{ name:"bit7.incdecNode"}, { name:"bit8.incdecNode"}]},
        { points:[{ name:"bit8.incdecNode"}, { name:"bit9.incdecNode"}]},
        { points:[{ name:"bit9.incdecNode"}, { name:"bitA.incdecNode"}]},
        { points:[{ name:"bitA.incdecNode"}, { name:"bitB.incdecNode"}]},
        { points:[{ name:"bitB.incdecNode"}, { name:"bitC.incdecNode"}]},
        { points:[{ name:"bitC.incdecNode"}, { name:"bitD.incdecNode"}]},
        { points:[{ name:"bitD.incdecNode"}, { name:"bitE.incdecJoint"}, { name:"bitE.xor2", io: "A", input: 0}]},

        { points:[{ name:"bit0.xor1", io: "out"}, { name:"tri", io: "I\u2080", input: 0}]},
        { points:[{ name:"bit1.xor1", io: "out"}, { name:"tri", io: "I\u2081", input: 1}]},
        { points:[{ name:"bit2.xor1", io: "out"}, { name:"tri", io: "I\u2082", input: 2}]},
        { points:[{ name:"bit3.xor1", io: "out"}, { name:"tri", io: "I\u2083", input: 3}]},
        { points:[{ name:"bit4.xor1", io: "out"}, { name:"tri", io: "I\u2084", input: 4}]},
        { points:[{ name:"bit5.xor1", io: "out"}, { name:"tri", io: "I\u2085", input: 5}]},
        { points:[{ name:"bit6.xor1", io: "out"}, { name:"tri", io: "I\u2086", input: 6}]},
        { points:[{ name:"bit7.xor1", io: "out"}, { name:"tri", io: "I\u2087", input: 7}]},
        { points:[{ name:"bit8.xor1", io: "out"}, { name:"tri", io: "I\u2088", input: 8}]},
        { points:[{ name:"bit9.xor1", io: "out"}, { name:"tri", io: "I\u2089", input: 9}]},
        { points:[{ name:"bitA.xor1", io: "out"}, { name:"tri", io: "I\u2081\u2080", input: 10}]},
        { points:[{ name:"bitB.xor1", io: "out"}, { name:"tri", io: "I\u2081\u2081", input: 11}]},
        { points:[{ name:"bitC.xor1", io: "out"}, { name:"tri", io: "I\u2081\u2082", input: 12}]},
        { points:[{ name:"bitD.xor1", io: "out"}, { name:"tri", io: "I\u2081\u2083", input: 13}]},
        { points:[{ name:"bitE.xor1", io: "out"}, { name:"tri", io: "I\u2081\u2084", input: 14}]},
        { points:[{ name:"bitF.xor1", io: "out"}, { name:"tri", io: "I\u2081\u2085", input: 15}]},

        { points:[{ name:"inValue", io: "bottom", output: "output"}, { name:"latch", io: "Input", input: "input"}], wide16: true, chars: 4},
        { points:[{ name:"clkButton", io: "bottom"}, { name:"clkJoint"}, { name:"latch", io: "Clock", input: "clk"}]},
        { points:[{ name:"enableOr", io: "out"}, { name:"tri", io: "Enable", input: "enable"}]},
        { points:[{ name:"decButton", io: "bottom"}, { name:"decNode"}]},
        { points:[{ name:"decNode"}, { name:"decJoint"}, { name:"enableOr", io: "B", input: 1}]},
        { points:[{ name:"incButton", io: "bottom"}, { name:"incJoint"}, { name:"enableOr", io: "A", input: 0}]},
        { points:[{ name:"tri", io: "Output", output: "output"}, { name:"outLight", io: "top"}], wide16: true, chars: 4}

    ]
}