// Chapter19SixteenByEightArray (c) Charles Petzold, 2024

let Chapter19SixteenByEightArray = 
{
    name: "Chapter19SixteenByEightArray",
    transform: { x: 0, y: 0, scale: 1, rotate: 0 },
    components:
        [
          { name:"byte0", type: "External", file: "Chapter19OneByteMemory", y: 0},
          { name:"byte1", type: "External", file: "Chapter19OneByteMemory", y: 125},  
          { name:"byte2", type: "External", file: "Chapter19OneByteMemory", y: 250},  
          { name:"byte3", type: "External", file: "Chapter19OneByteMemory", y: 375},  
          { name:"byte4", type: "External", file: "Chapter19OneByteMemory", y: 500},  
          { name:"byte5", type: "External", file: "Chapter19OneByteMemory", y: 625},  
          { name:"byte6", type: "External", file: "Chapter19OneByteMemory", y: 750},  
          { name:"byte7", type: "External", file: "Chapter19OneByteMemory", y: 875},  
          { name:"byte8", type: "External", file: "Chapter19OneByteMemory", y: 1000},  
          { name:"byte9", type: "External", file: "Chapter19OneByteMemory", y: 1125},  
          { name:"byteA", type: "External", file: "Chapter19OneByteMemory", y: 1250},  
          { name:"byteB", type: "External", file: "Chapter19OneByteMemory", y: 1375},  
          { name:"byteC", type: "External", file: "Chapter19OneByteMemory", y: 1500},  
          { name:"byteD", type: "External", file: "Chapter19OneByteMemory", y: 1625},  
          { name:"byteE", type: "External", file: "Chapter19OneByteMemory", y: 1750},  
          { name:"byteF", type: "External", file: "Chapter19OneByteMemory", y: 1875} 
      
        ],
    wires: [

        { points:[{ name:"byte0.bit7.buttonNode"}, { name:"byte1.bit7.buttonNode"}]},
        { points:[{ name:"byte1.bit7.buttonNode"}, { name:"byte2.bit7.buttonNode"}]},
        { points:[{ name:"byte2.bit7.buttonNode"}, { name:"byte3.bit7.buttonNode"}]},
        { points:[{ name:"byte3.bit7.buttonNode"}, { name:"byte4.bit7.buttonNode"}]},
        { points:[{ name:"byte4.bit7.buttonNode"}, { name:"byte5.bit7.buttonNode"}]},
        { points:[{ name:"byte5.bit7.buttonNode"}, { name:"byte6.bit7.buttonNode"}]},
        { points:[{ name:"byte6.bit7.buttonNode"}, { name:"byte7.bit7.buttonNode"}]},
        { points:[{ name:"byte7.bit7.buttonNode"}, { name:"byte8.bit7.buttonNode"}]},
        { points:[{ name:"byte8.bit7.buttonNode"}, { name:"byte9.bit7.buttonNode"}]},
        { points:[{ name:"byte9.bit7.buttonNode"}, { name:"byteA.bit7.buttonNode"}]},
        { points:[{ name:"byteA.bit7.buttonNode"}, { name:"byteB.bit7.buttonNode"}]},
        { points:[{ name:"byteB.bit7.buttonNode"}, { name:"byteC.bit7.buttonNode"}]},
        { points:[{ name:"byteC.bit7.buttonNode"}, { name:"byteD.bit7.buttonNode"}]},
        { points:[{ name:"byteD.bit7.buttonNode"}, { name:"byteE.bit7.buttonNode"}]},
        { points:[{ name:"byteE.bit7.buttonNode"}, { name:"byteF.bit7.buttonNode"}]},

        { points:[{ name:"byte0.bit6.buttonNode"}, { name:"byte1.bit6.buttonNode"}]},
        { points:[{ name:"byte1.bit6.buttonNode"}, { name:"byte2.bit6.buttonNode"}]},
        { points:[{ name:"byte2.bit6.buttonNode"}, { name:"byte3.bit6.buttonNode"}]},
        { points:[{ name:"byte3.bit6.buttonNode"}, { name:"byte4.bit6.buttonNode"}]},
        { points:[{ name:"byte4.bit6.buttonNode"}, { name:"byte5.bit6.buttonNode"}]},
        { points:[{ name:"byte5.bit6.buttonNode"}, { name:"byte6.bit6.buttonNode"}]},
        { points:[{ name:"byte6.bit6.buttonNode"}, { name:"byte7.bit6.buttonNode"}]},
        { points:[{ name:"byte7.bit6.buttonNode"}, { name:"byte8.bit6.buttonNode"}]},
        { points:[{ name:"byte8.bit6.buttonNode"}, { name:"byte9.bit6.buttonNode"}]},
        { points:[{ name:"byte9.bit6.buttonNode"}, { name:"byteA.bit6.buttonNode"}]},
        { points:[{ name:"byteA.bit6.buttonNode"}, { name:"byteB.bit6.buttonNode"}]},
        { points:[{ name:"byteB.bit6.buttonNode"}, { name:"byteC.bit6.buttonNode"}]},
        { points:[{ name:"byteC.bit6.buttonNode"}, { name:"byteD.bit6.buttonNode"}]},
        { points:[{ name:"byteD.bit6.buttonNode"}, { name:"byteE.bit6.buttonNode"}]},
        { points:[{ name:"byteE.bit6.buttonNode"}, { name:"byteF.bit6.buttonNode"}]},

        { points:[{ name:"byte0.bit5.buttonNode"}, { name:"byte1.bit5.buttonNode"}]},
        { points:[{ name:"byte1.bit5.buttonNode"}, { name:"byte2.bit5.buttonNode"}]},
        { points:[{ name:"byte2.bit5.buttonNode"}, { name:"byte3.bit5.buttonNode"}]},
        { points:[{ name:"byte3.bit5.buttonNode"}, { name:"byte4.bit5.buttonNode"}]},
        { points:[{ name:"byte4.bit5.buttonNode"}, { name:"byte5.bit5.buttonNode"}]},
        { points:[{ name:"byte5.bit5.buttonNode"}, { name:"byte6.bit5.buttonNode"}]},
        { points:[{ name:"byte6.bit5.buttonNode"}, { name:"byte7.bit5.buttonNode"}]},
        { points:[{ name:"byte7.bit5.buttonNode"}, { name:"byte8.bit5.buttonNode"}]},
        { points:[{ name:"byte8.bit5.buttonNode"}, { name:"byte9.bit5.buttonNode"}]},
        { points:[{ name:"byte9.bit5.buttonNode"}, { name:"byteA.bit5.buttonNode"}]},
        { points:[{ name:"byteA.bit5.buttonNode"}, { name:"byteB.bit5.buttonNode"}]},
        { points:[{ name:"byteB.bit5.buttonNode"}, { name:"byteC.bit5.buttonNode"}]},
        { points:[{ name:"byteC.bit5.buttonNode"}, { name:"byteD.bit5.buttonNode"}]},
        { points:[{ name:"byteD.bit5.buttonNode"}, { name:"byteE.bit5.buttonNode"}]},
        { points:[{ name:"byteE.bit5.buttonNode"}, { name:"byteF.bit5.buttonNode"}]},

        { points:[{ name:"byte0.bit4.buttonNode"}, { name:"byte1.bit4.buttonNode"}]},
        { points:[{ name:"byte1.bit4.buttonNode"}, { name:"byte2.bit4.buttonNode"}]},
        { points:[{ name:"byte2.bit4.buttonNode"}, { name:"byte3.bit4.buttonNode"}]},
        { points:[{ name:"byte3.bit4.buttonNode"}, { name:"byte4.bit4.buttonNode"}]},
        { points:[{ name:"byte4.bit4.buttonNode"}, { name:"byte5.bit4.buttonNode"}]},
        { points:[{ name:"byte5.bit4.buttonNode"}, { name:"byte6.bit4.buttonNode"}]},
        { points:[{ name:"byte6.bit4.buttonNode"}, { name:"byte7.bit4.buttonNode"}]},
        { points:[{ name:"byte7.bit4.buttonNode"}, { name:"byte8.bit4.buttonNode"}]},
        { points:[{ name:"byte8.bit4.buttonNode"}, { name:"byte9.bit4.buttonNode"}]},
        { points:[{ name:"byte9.bit4.buttonNode"}, { name:"byteA.bit4.buttonNode"}]},
        { points:[{ name:"byteA.bit4.buttonNode"}, { name:"byteB.bit4.buttonNode"}]},
        { points:[{ name:"byteB.bit4.buttonNode"}, { name:"byteC.bit4.buttonNode"}]},
        { points:[{ name:"byteC.bit4.buttonNode"}, { name:"byteD.bit4.buttonNode"}]},
        { points:[{ name:"byteD.bit4.buttonNode"}, { name:"byteE.bit4.buttonNode"}]},
        { points:[{ name:"byteE.bit4.buttonNode"}, { name:"byteF.bit4.buttonNode"}]},

        { points:[{ name:"byte0.bit3.buttonNode"}, { name:"byte1.bit3.buttonNode"}]},
        { points:[{ name:"byte1.bit3.buttonNode"}, { name:"byte2.bit3.buttonNode"}]},
        { points:[{ name:"byte2.bit3.buttonNode"}, { name:"byte3.bit3.buttonNode"}]},
        { points:[{ name:"byte3.bit3.buttonNode"}, { name:"byte4.bit3.buttonNode"}]},
        { points:[{ name:"byte4.bit3.buttonNode"}, { name:"byte5.bit3.buttonNode"}]},
        { points:[{ name:"byte5.bit3.buttonNode"}, { name:"byte6.bit3.buttonNode"}]},
        { points:[{ name:"byte6.bit3.buttonNode"}, { name:"byte7.bit3.buttonNode"}]},
        { points:[{ name:"byte7.bit3.buttonNode"}, { name:"byte8.bit3.buttonNode"}]},
        { points:[{ name:"byte8.bit3.buttonNode"}, { name:"byte9.bit3.buttonNode"}]},
        { points:[{ name:"byte9.bit3.buttonNode"}, { name:"byteA.bit3.buttonNode"}]},
        { points:[{ name:"byteA.bit3.buttonNode"}, { name:"byteB.bit3.buttonNode"}]},
        { points:[{ name:"byteB.bit3.buttonNode"}, { name:"byteC.bit3.buttonNode"}]},
        { points:[{ name:"byteC.bit3.buttonNode"}, { name:"byteD.bit3.buttonNode"}]},
        { points:[{ name:"byteD.bit3.buttonNode"}, { name:"byteE.bit3.buttonNode"}]},
        { points:[{ name:"byteE.bit3.buttonNode"}, { name:"byteF.bit3.buttonNode"}]},

        { points:[{ name:"byte0.bit2.buttonNode"}, { name:"byte1.bit2.buttonNode"}]},
        { points:[{ name:"byte1.bit2.buttonNode"}, { name:"byte2.bit2.buttonNode"}]},
        { points:[{ name:"byte2.bit2.buttonNode"}, { name:"byte3.bit2.buttonNode"}]},
        { points:[{ name:"byte3.bit2.buttonNode"}, { name:"byte4.bit2.buttonNode"}]},
        { points:[{ name:"byte4.bit2.buttonNode"}, { name:"byte5.bit2.buttonNode"}]},
        { points:[{ name:"byte5.bit2.buttonNode"}, { name:"byte6.bit2.buttonNode"}]},
        { points:[{ name:"byte6.bit2.buttonNode"}, { name:"byte7.bit2.buttonNode"}]},
        { points:[{ name:"byte7.bit2.buttonNode"}, { name:"byte8.bit2.buttonNode"}]},
        { points:[{ name:"byte8.bit2.buttonNode"}, { name:"byte9.bit2.buttonNode"}]},
        { points:[{ name:"byte9.bit2.buttonNode"}, { name:"byteA.bit2.buttonNode"}]},
        { points:[{ name:"byteA.bit2.buttonNode"}, { name:"byteB.bit2.buttonNode"}]},
        { points:[{ name:"byteB.bit2.buttonNode"}, { name:"byteC.bit2.buttonNode"}]},
        { points:[{ name:"byteC.bit2.buttonNode"}, { name:"byteD.bit2.buttonNode"}]},
        { points:[{ name:"byteD.bit2.buttonNode"}, { name:"byteE.bit2.buttonNode"}]},
        { points:[{ name:"byteE.bit2.buttonNode"}, { name:"byteF.bit2.buttonNode"}]},

        { points:[{ name:"byte0.bit1.buttonNode"}, { name:"byte1.bit1.buttonNode"}]},
        { points:[{ name:"byte1.bit1.buttonNode"}, { name:"byte2.bit1.buttonNode"}]},
        { points:[{ name:"byte2.bit1.buttonNode"}, { name:"byte3.bit1.buttonNode"}]},
        { points:[{ name:"byte3.bit1.buttonNode"}, { name:"byte4.bit1.buttonNode"}]},
        { points:[{ name:"byte4.bit1.buttonNode"}, { name:"byte5.bit1.buttonNode"}]},
        { points:[{ name:"byte5.bit1.buttonNode"}, { name:"byte6.bit1.buttonNode"}]},
        { points:[{ name:"byte6.bit1.buttonNode"}, { name:"byte7.bit1.buttonNode"}]},
        { points:[{ name:"byte7.bit1.buttonNode"}, { name:"byte8.bit1.buttonNode"}]},
        { points:[{ name:"byte8.bit1.buttonNode"}, { name:"byte9.bit1.buttonNode"}]},
        { points:[{ name:"byte9.bit1.buttonNode"}, { name:"byteA.bit1.buttonNode"}]},
        { points:[{ name:"byteA.bit1.buttonNode"}, { name:"byteB.bit1.buttonNode"}]},
        { points:[{ name:"byteB.bit1.buttonNode"}, { name:"byteC.bit1.buttonNode"}]},
        { points:[{ name:"byteC.bit1.buttonNode"}, { name:"byteD.bit1.buttonNode"}]},
        { points:[{ name:"byteD.bit1.buttonNode"}, { name:"byteE.bit1.buttonNode"}]},
        { points:[{ name:"byteE.bit1.buttonNode"}, { name:"byteF.bit1.buttonNode"}]},

        { points:[{ name:"byte0.bit0.buttonNode"}, { name:"byte1.bit0.buttonNode"}]},
        { points:[{ name:"byte1.bit0.buttonNode"}, { name:"byte2.bit0.buttonNode"}]},
        { points:[{ name:"byte2.bit0.buttonNode"}, { name:"byte3.bit0.buttonNode"}]},
        { points:[{ name:"byte3.bit0.buttonNode"}, { name:"byte4.bit0.buttonNode"}]},
        { points:[{ name:"byte4.bit0.buttonNode"}, { name:"byte5.bit0.buttonNode"}]},
        { points:[{ name:"byte5.bit0.buttonNode"}, { name:"byte6.bit0.buttonNode"}]},
        { points:[{ name:"byte6.bit0.buttonNode"}, { name:"byte7.bit0.buttonNode"}]},
        { points:[{ name:"byte7.bit0.buttonNode"}, { name:"byte8.bit0.buttonNode"}]},
        { points:[{ name:"byte8.bit0.buttonNode"}, { name:"byte9.bit0.buttonNode"}]},
        { points:[{ name:"byte9.bit0.buttonNode"}, { name:"byteA.bit0.buttonNode"}]},
        { points:[{ name:"byteA.bit0.buttonNode"}, { name:"byteB.bit0.buttonNode"}]},
        { points:[{ name:"byteB.bit0.buttonNode"}, { name:"byteC.bit0.buttonNode"}]},
        { points:[{ name:"byteC.bit0.buttonNode"}, { name:"byteD.bit0.buttonNode"}]},
        { points:[{ name:"byteD.bit0.buttonNode"}, { name:"byteE.bit0.buttonNode"}]},
        { points:[{ name:"byteE.bit0.buttonNode"}, { name:"byteF.bit0.buttonNode"}]},

        { points:[{ name:"byte0.writeANode"}, { name:"byte1.writeANode"}]},
        { points:[{ name:"byte1.writeANode"}, { name:"byte2.writeANode"}]},
        { points:[{ name:"byte2.writeANode"}, { name:"byte3.writeANode"}]},
        { points:[{ name:"byte3.writeANode"}, { name:"byte4.writeANode"}]},
        { points:[{ name:"byte4.writeANode"}, { name:"byte5.writeANode"}]},
        { points:[{ name:"byte5.writeANode"}, { name:"byte6.writeANode"}]},
        { points:[{ name:"byte6.writeANode"}, { name:"byte7.writeANode"}]},
        { points:[{ name:"byte7.writeANode"}, { name:"byte8.writeANode"}]},
        { points:[{ name:"byte8.writeANode"}, { name:"byte9.writeANode"}]},
        { points:[{ name:"byte9.writeANode"}, { name:"byteA.writeANode"}]},
        { points:[{ name:"byteA.writeANode"}, { name:"byteB.writeANode"}]},
        { points:[{ name:"byteB.writeANode"}, { name:"byteC.writeANode"}]},
        { points:[{ name:"byteC.writeANode"}, { name:"byteD.writeANode"}]},
        { points:[{ name:"byteD.writeANode"}, { name:"byteE.writeANode"}]},
        { points:[{ name:"byteD.writeANode"}, { name:"byteF.writeANode"}]},

        { points:[{ name:"byteF.bit7.emitterNode"}, { name:"byteE.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit7.emitterNode"}, { name:"byteD.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit7.emitterNode"}, { name:"byteC.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit7.emitterNode"}, { name:"byteB.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit7.emitterNode"}, { name:"byteA.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit7.emitterNode"}, { name:"byte9.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit7.emitterNode"}, { name:"byte8.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit7.emitterNode"}, { name:"byte7.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit7.emitterNode"}, { name:"byte6.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit7.emitterNode"}, { name:"byte5.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit7.emitterNode"}, { name:"byte4.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit7.emitterNode"}, { name:"byte3.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit7.emitterNode"}, { name:"byte2.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit7.emitterNode"}, { name:"byte1.bit7.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit7.emitterNode"}, { name:"byte0.bit7.emitterNode", input: 1}]},

        { points:[{ name:"byteF.bit6.emitterNode"}, { name:"byteE.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit6.emitterNode"}, { name:"byteD.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit6.emitterNode"}, { name:"byteC.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit6.emitterNode"}, { name:"byteB.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit6.emitterNode"}, { name:"byteA.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit6.emitterNode"}, { name:"byte9.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit6.emitterNode"}, { name:"byte8.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit6.emitterNode"}, { name:"byte7.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit6.emitterNode"}, { name:"byte6.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit6.emitterNode"}, { name:"byte5.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit6.emitterNode"}, { name:"byte4.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit6.emitterNode"}, { name:"byte3.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit6.emitterNode"}, { name:"byte2.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit6.emitterNode"}, { name:"byte1.bit6.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit6.emitterNode"}, { name:"byte0.bit6.emitterNode", input: 1}]},

        { points:[{ name:"byteF.bit5.emitterNode"}, { name:"byteE.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit5.emitterNode"}, { name:"byteD.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit5.emitterNode"}, { name:"byteC.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit5.emitterNode"}, { name:"byteB.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit5.emitterNode"}, { name:"byteA.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit5.emitterNode"}, { name:"byte9.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit5.emitterNode"}, { name:"byte8.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit5.emitterNode"}, { name:"byte7.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit5.emitterNode"}, { name:"byte6.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit5.emitterNode"}, { name:"byte5.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit5.emitterNode"}, { name:"byte4.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit5.emitterNode"}, { name:"byte3.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit5.emitterNode"}, { name:"byte2.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit5.emitterNode"}, { name:"byte1.bit5.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit5.emitterNode"}, { name:"byte0.bit5.emitterNode", input: 1}]},

        { points:[{ name:"byteF.bit4.emitterNode"}, { name:"byteE.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit4.emitterNode"}, { name:"byteD.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit4.emitterNode"}, { name:"byteC.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit4.emitterNode"}, { name:"byteB.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit4.emitterNode"}, { name:"byteA.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit4.emitterNode"}, { name:"byte9.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit4.emitterNode"}, { name:"byte8.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit4.emitterNode"}, { name:"byte7.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit4.emitterNode"}, { name:"byte6.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit4.emitterNode"}, { name:"byte5.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit4.emitterNode"}, { name:"byte4.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit4.emitterNode"}, { name:"byte3.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit4.emitterNode"}, { name:"byte2.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit4.emitterNode"}, { name:"byte1.bit4.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit4.emitterNode"}, { name:"byte0.bit4.emitterNode", input: 1}]},

        { points:[{ name:"byteF.bit3.emitterNode"}, { name:"byteE.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit3.emitterNode"}, { name:"byteD.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit3.emitterNode"}, { name:"byteC.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit3.emitterNode"}, { name:"byteB.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit3.emitterNode"}, { name:"byteA.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit3.emitterNode"}, { name:"byte9.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit3.emitterNode"}, { name:"byte8.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit3.emitterNode"}, { name:"byte7.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit3.emitterNode"}, { name:"byte6.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit3.emitterNode"}, { name:"byte5.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit3.emitterNode"}, { name:"byte4.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit3.emitterNode"}, { name:"byte3.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit3.emitterNode"}, { name:"byte2.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit3.emitterNode"}, { name:"byte1.bit3.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit3.emitterNode"}, { name:"byte0.bit3.emitterNode", input: 1}]},

        { points:[{ name:"byteF.bit2.emitterNode"}, { name:"byteE.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit2.emitterNode"}, { name:"byteD.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit2.emitterNode"}, { name:"byteC.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit2.emitterNode"}, { name:"byteB.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit2.emitterNode"}, { name:"byteA.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit2.emitterNode"}, { name:"byte9.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit2.emitterNode"}, { name:"byte8.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit2.emitterNode"}, { name:"byte7.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit2.emitterNode"}, { name:"byte6.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit2.emitterNode"}, { name:"byte5.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit2.emitterNode"}, { name:"byte4.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit2.emitterNode"}, { name:"byte3.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit2.emitterNode"}, { name:"byte2.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit2.emitterNode"}, { name:"byte1.bit2.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit2.emitterNode"}, { name:"byte0.bit2.emitterNode", input: 1}]},

        { points:[{ name:"byteF.bit1.emitterNode"}, { name:"byteE.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit1.emitterNode"}, { name:"byteD.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit1.emitterNode"}, { name:"byteC.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit1.emitterNode"}, { name:"byteB.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit1.emitterNode"}, { name:"byteA.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit1.emitterNode"}, { name:"byte9.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit1.emitterNode"}, { name:"byte8.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit1.emitterNode"}, { name:"byte7.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit1.emitterNode"}, { name:"byte6.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit1.emitterNode"}, { name:"byte5.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit1.emitterNode"}, { name:"byte4.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit1.emitterNode"}, { name:"byte3.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit1.emitterNode"}, { name:"byte2.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit1.emitterNode"}, { name:"byte1.bit1.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit1.emitterNode"}, { name:"byte0.bit1.emitterNode", input: 1}]},

        { points:[{ name:"byteF.bit0.emitterNode"}, { name:"byteE.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byteE.bit0.emitterNode"}, { name:"byteD.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byteD.bit0.emitterNode"}, { name:"byteC.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byteC.bit0.emitterNode"}, { name:"byteB.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byteB.bit0.emitterNode"}, { name:"byteA.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byteA.bit0.emitterNode"}, { name:"byte9.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte9.bit0.emitterNode"}, { name:"byte8.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte8.bit0.emitterNode"}, { name:"byte7.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte7.bit0.emitterNode"}, { name:"byte6.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte6.bit0.emitterNode"}, { name:"byte5.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte5.bit0.emitterNode"}, { name:"byte4.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte4.bit0.emitterNode"}, { name:"byte3.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte3.bit0.emitterNode"}, { name:"byte2.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte2.bit0.emitterNode"}, { name:"byte1.bit0.emitterNode", input: 1}]},
        { points:[{ name:"byte1.bit0.emitterNode"}, { name:"byte0.bit0.emitterNode", input: 1}]}
    ]
}
