// Chapter19EightByOneRam (c) Charles Petzold, 2024

let Chapter19EightByOneRam = 
{
    name: "Chapter19EightByOneRam",
    transform: { x: 375, y: 400, scale: 1, rotate: 0 },
    wireCurveRadius: 5,
    nodeRadius: 3,
    propagationDelay: 0,
    components:
        [
            { name:"bit7", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 0},
            { name:"bit6", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 200},
            { name:"bit5", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 400},
            { name:"bit4", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 600},
            { name:"bit3", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 800},
            { name:"bit2", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 1000},
            { name:"bit1", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 1200},
            { name:"bit0", type: "External", file: "Chapter19MemoryBit", scale: 0.25, x: 1400},

            { name:"decoder", type: "External", file: "Chapter19EightAnds", y: -100, x: -83},
            { name:"selector", type: "External", file: "Chapter19EightAnds", y: 225, x: -75 },

            { name:"writeButton", type: "MomentaryButton", x: 625, y: -325},
            { name:"write", type: "Label", text: "Write", y: -50, relative: {xy: { name:"writeButton"}}},

            { name:"switchA0", type: "DigitButton", x: -800, relative: {xy: { name:"writeButton"}, y: { name:"switchW"}}},
            { name:"switchA1", type: "DigitButton", x: -75, relative: {xy: { name:"switchA0"}}},
            { name:"switchA2", type: "DigitButton", x: -75, relative: {xy: { name:"switchA1"}}},

            { name:"swLabelA0", type: "Label", text: "A0", relative: {x: { name:"switchA0"}, y: { name:"write"}}},
            { name:"swLabelA1", type: "Label", text: "A1", relative: {x: { name:"switchA1"}, y: { name:"write"}}},
            { name:"swLabelA2", type: "Label", text: "A2", relative: {x: { name:"switchA2"}, y: { name:"write"}}},

            { name:"a0Node0", type: "Node", relative: {x: { name:"switchA0"}, y: { name:"decoder.and7Node0"}}},
            { name:"a0Node1", type: "Node", relative: {x: { name:"switchA0"}, y: { name:"decoder.inv0"}}},
            { name:"a0Node2", type: "Node", relative: {x: { name:"switchA0"}, y: { name:"selector.and7Node0"}}},
            { name:"a0Joint3", type: "Joint", relative: {x: { name:"switchA0"}, y: { name:"selector.inv0"}}},

            { name:"a1Node0", type: "Node", relative: {x: { name:"switchA1"}, y: { name:"decoder.and7Node1"}}},
            { name:"a1Node1", type: "Node", relative: {x: { name:"switchA1"}, y: { name:"decoder.inv1"}}},
            { name:"a1Node2", type: "Node", relative: {x: { name:"switchA1"}, y: { name:"selector.and7Node1"}}},
            { name:"a1Joint3", type: "Joint", relative: {x: { name:"switchA1"}, y: { name:"selector.inv1"}}},

            { name:"a2Node0", type: "Node", relative: {x: { name:"switchA2"}, y: { name:"decoder.and7Node2"}}},
            { name:"a2Node1", type: "Node", relative: {x: { name:"switchA2"}, y: { name:"decoder.inv2"}}},
            { name:"a2Node2", type: "Node", relative: {x: { name:"switchA2"}, y: { name:"selector.and7Node2"}}},
            { name:"a2Joint3", type: "Joint", relative: {x: { name:"switchA2"}, y: { name:"selector.inv2"}}},

            { name:"writeNode", type: "Node", y: 50, relative: {xy: { name:"writeButton", io: "bottom"}}},
            { name: "writeJoint7", type: "Joint", relative: {x: { name:"decoder.and7", io: "1/4"}, y: { name:"writeNode"}}},
            { name: "writeNode6", type: "Node", relative: {x: { name:"decoder.and6", io: "1/4"}, y: { name:"writeNode"}}},
            { name: "writeNode5", type: "Node", relative: {x: { name:"decoder.and5", io: "1/4"}, y: { name:"writeNode"}}},
            { name: "writeNode4", type: "Node", relative: {x: { name:"decoder.and4", io: "1/4"}, y: { name:"writeNode"}}},
            { name: "writeNode3", type: "Node", relative: {x: { name:"decoder.and3", io: "1/4"}, y: { name:"writeNode"}}},
            { name: "writeNode2", type: "Node", relative: {x: { name:"decoder.and2", io: "1/4"}, y: { name:"writeNode"}}},
            { name: "writeNode1", type: "Node", relative: {x: { name:"decoder.and1", io: "1/4"}, y: { name:"writeNode"}}},
            { name: "writeJoint0", type: "Joint", relative: {x: { name:"decoder.and0", io: "1/4"}, y: { name:"writeNode"}}},

            { name:"diButton", type: "DigitButton", x: 800, relative: {xy: { name:"writeButton"}}},
            { name:"di", type: "Label", text: "Data In", relative: {x: { name:"diButton"}, y: { name:"write"}}},

            { name:"diJoint", type: "Joint", y: 275, relative: {xy: { name:"diButton"}}},
            { name:"di0Node", type: "Node", relative: {x: { name:"bit0.diJoint1"}, y: { name:"diJoint"}}},
            { name:"di1Node", type: "Node", relative: {x: { name:"bit1.diJoint1"}, y: { name:"diJoint"}}},
            { name:"di2Node", type: "Node", relative: {x: { name:"bit2.diJoint1"}, y: { name:"diJoint"}}},
            { name:"di3Node", type: "Node", relative: {x: { name:"bit3.diJoint1"}, y: { name:"diJoint"}}},
            { name:"di4Node", type: "Node", relative: {x: { name:"bit4.diJoint1"}, y: { name:"diJoint"}}},
            { name:"di5Node", type: "Node", relative: {x: { name:"bit5.diJoint1"}, y: { name:"diJoint"}}},
            { name:"di6Node", type: "Node", relative: {x: { name:"bit6.diJoint1"}, y: { name:"diJoint"}}},
            { name:"di7Joint", type: "Joint", relative: {x: { name:"bit7.diJoint1"}, y: { name:"diJoint"}}},
            
            { name:"do7Joint2", type: "Joint", y: 100, relative: {xy: { name:"bit7.doJoint1"}}},
            { name:"do7Joint3", type: "Joint", relative: {y: { name:"do7Joint2"}, x: { name:"selector.and7", io: "1/4"}}},
            { name:"do6Joint2", type: "Joint", relative: {x: { name:"bit6.doJoint1"}, y: { name:"do7Joint2"}}},
            { name:"do6Joint3", type: "Joint", relative: {y: { name:"do6Joint2"}, x: { name:"selector.and6", io: "1/4"}}},
            { name:"do5Joint2", type: "Joint", relative: {x: { name:"bit5.doJoint1"}, y: { name:"do7Joint2"}}},
            { name:"do5Joint3", type: "Joint", relative: {y: { name:"do5Joint2"}, x: { name:"selector.and5", io: "1/4"}}},
            { name:"do4Joint2", type: "Joint", relative: {x: { name:"bit4.doJoint1"}, y: { name:"do7Joint2"}}},
            { name:"do4Joint3", type: "Joint", relative: {y: { name:"do4Joint2"}, x: { name:"selector.and4", io: "1/4"}}},
            { name:"do3Joint2", type: "Joint", relative: {x: { name:"bit3.doJoint1"}, y: { name:"do7Joint2"}}},
            { name:"do3Joint3", type: "Joint", relative: {y: { name:"do3Joint2"}, x: { name:"selector.and3", io: "1/4"}}},
            { name:"do2Joint2", type: "Joint", relative: {x: { name:"bit2.doJoint1"}, y: { name:"do7Joint2"}}},
            { name:"do2Joint3", type: "Joint", relative: {y: { name:"do2Joint2"}, x: { name:"selector.and2", io: "1/4"}}},
            { name:"do1Joint2", type: "Joint", relative: {x: { name:"bit1.doJoint1"}, y: { name:"do7Joint2"}}},
            { name:"do1Joint3", type: "Joint", relative: {y: { name:"do1Joint2"}, x: { name:"selector.and1", io: "1/4"}}},
            { name:"do0Joint2", type: "Joint", relative: {x: { name:"bit0.doJoint1"}, y: { name:"do7Joint2"}}},
            { name:"do0Joint3", type: "Joint", relative: {y: { name:"do0Joint2"}, x: { name:"selector.and0", io: "1/4"}}},

            { name:"bigOr", type: "OrGate", inputs: 8, rotate: 90, y: 675, relative: {xy: { name:"writeButton"}}},

            { name:"sel7Joint2", type: "Joint", y: -30, relative: {xy: { name:"bigOr", io: "8/8"}}},
            { name:"sel6Joint2", type: "Joint", y: -40, relative: {xy: { name:"bigOr", io: "7/8"}}},
            { name:"sel5Joint2", type: "Joint", y: -50, relative: {xy: { name:"bigOr", io: "6/8"}}},
            { name:"sel4Joint2", type: "Joint", y: -60, relative: {xy: { name:"bigOr", io: "5/8"}}},
            { name:"sel3Joint2", type: "Joint", y: -60, relative: {xy: { name:"bigOr", io: "4/8"}}},
            { name:"sel2Joint2", type: "Joint", y: -50, relative: {xy: { name:"bigOr", io: "3/8"}}},
            { name:"sel1Joint2", type: "Joint", y: -40, relative: {xy: { name:"bigOr", io: "2/8"}}},
            { name:"sel0Joint2", type: "Joint", y: -30, relative: {xy: { name:"bigOr", io: "1/8"}}},

            { name:"sel7Joint1", type: "Joint", relative: {x: { name:"selector.and7", io: "out"}, y: { name:"sel7Joint2"}}},
            { name:"sel6Joint1", type: "Joint", relative: {x: { name:"selector.and6", io: "out"}, y: { name:"sel6Joint2"}}},
            { name:"sel5Joint1", type: "Joint", relative: {x: { name:"selector.and5", io: "out"}, y: { name:"sel5Joint2"}}},
            { name:"sel4Joint1", type: "Joint", relative: {x: { name:"selector.and4", io: "out"}, y: { name:"sel4Joint2"}}},
            { name:"sel3Joint1", type: "Joint", relative: {x: { name:"selector.and3", io: "out"}, y: { name:"sel3Joint2"}}},
            { name:"sel2Joint1", type: "Joint", relative: {x: { name:"selector.and2", io: "out"}, y: { name:"sel2Joint2"}}},
            { name:"sel1Joint1", type: "Joint", relative: {x: { name:"selector.and1", io: "out"}, y: { name:"sel1Joint2"}}},
            { name:"sel0Joint1", type: "Joint", relative: {x: { name:"selector.and0", io: "out"}, y: { name:"sel0Joint2"}}},

            { name:"light", type: "BitLight", y: 75, relative: {xy: { name:"bigOr", io: "out"}}},
            { name:"do", type: "Label", text: "Data Out", y: 50, relative: {xy: { name:"light"}}}

        ],
        wires:
        [
            { points:[{ name:"switchA0", io: "bottom"}, { name:"a0Node0"}]},
            { points:[{ name:"a0Node0"}, { name:"a0Node1"}]},
            { points:[{ name:"a0Node1"}, { name:"a0Node2"}]},
            { points:[{ name:"a0Node0"}, { name:"decoder.and7Node0"}]},
            { points:[{ name:"a0Node1"}, { name:"decoder.inv0"}]},
            { points:[{ name:"a0Node2"}, { name:"selector.and7Node0"}]},
            { points:[{ name:"a0Node2"}, { name:"a0Joint3"}, { name:"selector.inv0"}]},

            { points:[{ name:"switchA1", io: "bottom"}, { name:"a1Node0"}]},
            { points:[{ name:"a1Node0"}, { name:"a1Node1"}]},
            { points:[{ name:"a1Node1"}, { name:"a1Node2"}]},
            { points:[{ name:"a1Node0"}, { name:"decoder.and7Node1"}]},
            { points:[{ name:"a1Node1"}, { name:"decoder.inv1"}]},
            { points:[{ name:"a1Node2"}, { name:"selector.and7Node1"}]},
            { points:[{ name:"a1Node2"}, { name:"a1Joint3"}, { name:"selector.inv1"}]},

            { points:[{ name:"switchA2", io: "bottom"}, { name:"a2Node0"}]},
            { points:[{ name:"a2Node0"}, { name:"a2Node1"}]},
            { points:[{ name:"a2Node1"}, { name:"a2Node2"}]},
            { points:[{ name:"a2Node0"}, { name:"decoder.and7Node2"}]},
            { points:[{ name:"a2Node1"}, { name:"decoder.inv2"}]},
            { points:[{ name:"a2Node2"}, { name:"selector.and7Node2"}]},
            { points:[{ name:"a2Node2"}, { name:"a2Joint3"}, { name:"selector.inv2"}]},

            { points: [{ name:"writeButton", io: "bottom"}, { name:"writeNode"}]},
            { points: [{ name:"writeNode"}, { name:"writeNode3"}]},
            { points: [{ name:"writeNode3"}, { name:"decoder.and3", io: "1/4", input: 0}]},
            { points: [{ name:"writeNode3"}, { name:"writeNode2"}]},
            { points: [{ name:"writeNode2"}, { name:"decoder.and2", io: "1/4", input: 0}]},
            { points: [{ name:"writeNode2"}, { name:"writeNode1"}]},
            { points: [{ name:"writeNode1"}, { name:"decoder.and1", io: "1/4", input: 0}]},
            { points: [{ name:"writeNode1"}, { name:"writeJoint0"}, { name:"decoder.and0", io: "1/4", input: 0}]},

            { points: [{ name:"writeNode"}, { name:"writeNode4"}]},
            { points: [{ name:"writeNode4"}, { name:"decoder.and4", io: "1/4", input: 0}]},
            { points: [{ name:"writeNode4"}, { name:"writeNode5"}]},
            { points: [{ name:"writeNode5"}, { name:"decoder.and5", io: "1/4", input: 0}]},
            { points: [{ name:"writeNode5"}, { name:"writeNode6"}]},
            { points: [{ name:"writeNode6"}, { name:"decoder.and6", io: "1/4", input: 0}]},
            { points: [{ name:"writeNode6"}, { name:"writeJoint7"}, { name:"decoder.and7", io: "1/4", input: 0}]},

            { points: [{ name:"decoder.and7", io: "out"}, { name:"bit7.writeNode"}]},
            { points: [{ name:"decoder.and6", io: "out"}, { name:"bit6.writeNode"}]},
            { points: [{ name:"decoder.and5", io: "out"}, { name:"bit5.writeNode"}]},
            { points: [{ name:"decoder.and4", io: "out"}, { name:"bit4.writeNode"}]},
            { points: [{ name:"decoder.and3", io: "out"}, { name:"bit3.writeNode"}]},
            { points: [{ name:"decoder.and2", io: "out"}, { name:"bit2.writeNode"}]},
            { points: [{ name:"decoder.and1", io: "out"}, { name:"bit1.writeNode"}]},
            { points: [{ name:"decoder.and0", io: "out"}, { name:"bit0.writeNode"}]},

            { points:[{ name:"diButton", io: "bottom"}, { name:"diJoint"}, { name:"di0Node"}]},
            { points:[{ name:"di0Node"}, { name:"di1Node"}]},
            { points:[{ name:"di1Node"}, { name:"di2Node"}]},
            { points:[{ name:"di2Node"}, { name:"di3Node"}]},
            { points:[{ name:"di3Node"}, { name:"di4Node"}]},
            { points:[{ name:"di4Node"}, { name:"di5Node"}]},
            { points:[{ name:"di5Node"}, { name:"di6Node"}]},

            { points:[{ name:"di0Node"}, { name:"bit0.diJoint1"}, { name:"bit0.invNode"}]},
            { points:[{ name:"di1Node"}, { name:"bit1.diJoint1"}, { name:"bit1.invNode"}]},
            { points:[{ name:"di2Node"}, { name:"bit2.diJoint1"}, { name:"bit2.invNode"}]},
            { points:[{ name:"di3Node"}, { name:"bit3.diJoint1"}, { name:"bit3.invNode"}]},
            { points:[{ name:"di4Node"}, { name:"bit4.diJoint1"}, { name:"bit4.invNode"}]},
            { points:[{ name:"di5Node"}, { name:"bit5.diJoint1"}, { name:"bit5.invNode"}]},
            { points:[{ name:"di6Node"}, { name:"bit6.diJoint1"}, { name:"bit6.invNode"}]},
            { points:[{ name:"di6Node"}, { name:"di7Joint"}, { name:"bit7.diJoint1"}, { name:"bit7.invNode"}]},

            { points: [{ name:"bit7.node1"}, { name:"bit7.doJoint1"}, { name:"do7Joint2"}, { name:"do7Joint3"}, { name:"selector.and7", io: "1/4", input: 0}]},
            { points: [{ name:"bit6.node1"}, { name:"bit6.doJoint1"}, { name:"do6Joint2"}, { name:"do6Joint3"}, { name:"selector.and6", io: "1/4", input: 0}]},
            { points: [{ name:"bit5.node1"}, { name:"bit5.doJoint1"}, { name:"do5Joint2"}, { name:"do5Joint3"}, { name:"selector.and5", io: "1/4", input: 0}]},
            { points: [{ name:"bit4.node1"}, { name:"bit4.doJoint1"}, { name:"do4Joint2"}, { name:"do4Joint3"}, { name:"selector.and4", io: "1/4", input: 0}]},
            { points: [{ name:"bit3.node1"}, { name:"bit3.doJoint1"}, { name:"do3Joint2"}, { name:"do3Joint3"}, { name:"selector.and3", io: "1/4", input: 0}]},
            { points: [{ name:"bit2.node1"}, { name:"bit2.doJoint1"}, { name:"do2Joint2"}, { name:"do2Joint3"}, { name:"selector.and2", io: "1/4", input: 0}]},
            { points: [{ name:"bit1.node1"}, { name:"bit1.doJoint1"}, { name:"do1Joint2"}, { name:"do1Joint3"}, { name:"selector.and1", io: "1/4", input: 0}]},
            { points: [{ name:"bit0.node1"}, { name:"bit0.doJoint1"}, { name:"do0Joint2"}, { name:"do0Joint3"}, { name:"selector.and0", io: "1/4", input: 0}]},

            { points:[{ name:"selector.and7", io: "out"}, { name:"sel7Joint1"}, { name:"sel7Joint2"}, { name:"bigOr", io: "8/8", input: 7}]},
            { points:[{ name:"selector.and6", io: "out"}, { name:"sel6Joint1"}, { name:"sel6Joint2"}, { name:"bigOr", io: "7/8", input: 6}]},
            { points:[{ name:"selector.and5", io: "out"}, { name:"sel5Joint1"}, { name:"sel5Joint2"}, { name:"bigOr", io: "6/8", input: 5}]},
            { points:[{ name:"selector.and4", io: "out"}, { name:"sel4Joint1"}, { name:"sel4Joint2"}, { name:"bigOr", io: "5/8", input: 4}]},
            { points:[{ name:"selector.and3", io: "out"}, { name:"sel3Joint1"}, { name:"sel3Joint2"}, { name:"bigOr", io: "4/8", input: 3}]},
            { points:[{ name:"selector.and2", io: "out"}, { name:"sel2Joint1"}, { name:"sel2Joint2"}, { name:"bigOr", io: "3/8", input: 2}]},
            { points:[{ name:"selector.and1", io: "out"}, { name:"sel1Joint1"}, { name:"sel1Joint2"}, { name:"bigOr", io: "2/8", input: 1}]},
            { points:[{ name:"selector.and0", io: "out"}, { name:"sel0Joint1"}, { name:"sel0Joint2"}, { name:"bigOr", io: "1/8", input: 0}]},

            { points:[{ name:"bigOr", io: "out"}, { name:"light", io: "top"}]}
        ]
    }