// Chapter19FourToSixteenDecoder.json.js (c) Charles Petzold, 2024

let Chapter19FourToSixteenDecoder = 
{
    name: "Chapter19FourToSixteenDecoder",
    components: 
      [
        { name: "and0", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1875},
        { name: "and1", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1750},
        { name: "and2", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1625},
        { name: "and3", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1500},
        { name: "and4", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1375},
        { name: "and5", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1250},
        { name: "and6", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1125},
        { name: "and7", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 1000},
        { name: "and8", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 875},
        { name: "and9", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 750},
        { name: "andA", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 625},
        { name: "andB", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 500},
        { name: "andC", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 375},
        { name: "andD", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 250},
        { name: "andE", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 125},
        { name: "andF", type: "AndGate", inputs: 4, scale: 0.4, rotate: 90, x: 0},
   
        { name:"jointf0", type: "Joint", y: -10, relative: {xy: { name:"andF", io: "1/4"}}},
        { name:"jointf1", type: "Joint", y: -20, relative: {xy: { name:"andF", io: "2/4"}}},
        { name:"jointf2", type: "Joint", y: -30, relative: {xy: { name:"andF", io: "3/4"}}},
        { name:"jointf3", type: "Joint", y: -40, relative: {xy: { name:"andF", io: "4/4"}}},
  
        { name:"joint00", type: "Joint", y: -60, relative: {xy: { name:"and0", io: "1/4"}}},
        { name:"joint01", type: "Joint", y: -70, relative: {xy: { name:"and0", io: "2/4"}}},
        { name:"joint02", type: "Joint", y: -80, relative: {xy: { name:"and0", io: "3/4"}}},
        { name:"joint03", type: "Joint", y: -90, relative: {xy: { name:"and0", io: "4/4"}}},
  
        { name:"jointe0", type: "Joint", relative: {x: { name:"andE", io: "1/4"}, y: { name:"joint00"}}},
        { name:"nodee1", type: "Node", relative: {x: { name:"andE", io: "2/4"}, y: { name:"jointf1"}}},
        { name:"nodee2", type: "Node", relative: {x: { name:"andE", io: "3/4"}, y: { name:"jointf2"}}},
        { name:"nodee3", type: "Node", relative: {x: { name:"andE", io: "4/4"}, y: { name:"jointf3"}}},
    
        { name:"noded0", type: "Node", relative: {x: { name:"andD", io: "1/4"}, y: { name:"jointf0"}}},
        { name:"jointd1", type: "Joint", relative: {x: { name:"andD", io: "2/4"}, y: { name:"joint01"}}},
        { name:"noded2", type: "Node", relative: {x: { name:"andD", io: "3/4"}, y: { name:"jointf2"}}},
        { name:"noded3", type: "Node", relative: {x: { name:"andD", io: "4/4"}, y: { name:"jointf3"}}},
  
        { name:"nodec0", type: "Node", relative: {x: { name:"andC", io: "1/4"}, y: { name:"joint00"}}},
        { name:"nodec1", type: "Node", relative: {x: { name:"andC", io: "2/4"}, y: { name:"joint01"}}},
        { name:"nodec2", type: "Node", relative: {x: { name:"andC", io: "3/4"}, y: { name:"jointf2"}}},
        { name:"nodec3", type: "Node", relative: {x: { name:"andC", io: "4/4"}, y: { name:"jointf3"}}},
  
        { name:"nodeb0", type: "Node", relative: {x: { name:"andB", io: "1/4"}, y: { name:"jointf0"}}},
        { name:"nodeb1", type: "Node", relative: {x: { name:"andB", io: "2/4"}, y: { name:"jointf1"}}},
        { name:"nodeb2", type: "Node", relative: {x: { name:"andB", io: "3/4"}, y: { name:"joint02"}}},
        { name:"nodeb3", type: "Node", relative: {x: { name:"andB", io: "4/4"}, y: { name:"jointf3"}}},
  
        { name:"nodea0", type: "Node", relative: {x: { name:"andA", io: "1/4"}, y: { name:"joint00"}}},
        { name:"nodea1", type: "Node", relative: {x: { name:"andA", io: "2/4"}, y: { name:"jointf1"}}},
        { name:"nodea2", type: "Node", relative: {x: { name:"andA", io: "3/4"}, y: { name:"joint02"}}},
        { name:"nodea3", type: "Node", relative: {x: { name:"andA", io: "4/4"}, y: { name:"jointf3"}}},
  
        { name:"node90", type: "Node", relative: {x: { name:"and9", io: "1/4"}, y: { name:"jointf0"}}},
        { name:"node91", type: "Node", relative: {x: { name:"and9", io: "2/4"}, y: { name:"joint01"}}},
        { name:"node92", type: "Node", relative: {x: { name:"and9", io: "3/4"}, y: { name:"joint02"}}},
        { name:"node93", type: "Node", relative: {x: { name:"and9", io: "4/4"}, y: { name:"jointf3"}}},
  
        { name:"node80", type: "Node", relative: {x: { name:"and8", io: "1/4"}, y: { name:"joint00"}}},
        { name:"node81", type: "Node", relative: {x: { name:"and8", io: "2/4"}, y: { name:"joint01"}}},
        { name:"node82", type: "Node", relative: {x: { name:"and8", io: "3/4"}, y: { name:"joint02"}}},
        { name:"joint83", type: "Joint", relative: {x: { name:"and8", io: "4/4"}, y: { name:"jointf3"}}},
  
        { name:"node70", type: "Node", relative: {x: { name:"and7", io: "1/4"}, y: { name:"jointf0"}}},
        { name:"node71", type: "Node", relative: {x: { name:"and7", io: "2/4"}, y: { name:"jointf1"}}},
        { name:"node72", type: "Node", relative: {x: { name:"and7", io: "3/4"}, y: { name:"jointf2"}}},
        { name:"node73", type: "Node", relative: {x: { name:"and7", io: "4/4"}, y: { name:"joint03"}}},
  
        { name:"node60", type: "Node", relative: {x: { name:"and6", io: "1/4"}, y: { name:"joint00"}}},
        { name:"node61", type: "Node", relative: {x: { name:"and6", io: "2/4"}, y: { name:"jointf1"}}},
        { name:"node62", type: "Node", relative: {x: { name:"and6", io: "3/4"}, y: { name:"jointf2"}}},
        { name:"node63", type: "Node", relative: {x: { name:"and6", io: "4/4"}, y: { name:"joint03"}}},
  
        { name:"node50", type: "Node", relative: {x: { name:"and5", io: "1/4"}, y: { name:"jointf0"}}},
        { name:"node51", type: "Node", relative: {x: { name:"and5", io: "2/4"}, y: { name:"joint01"}}},
        { name:"node52", type: "Node", relative: {x: { name:"and5", io: "3/4"}, y: { name:"jointf2"}}},
        { name:"node53", type: "Node", relative: {x: { name:"and5", io: "4/4"}, y: { name:"joint03"}}},
  
        { name:"node40", type: "Node", relative: {x: { name:"and4", io: "1/4"}, y: { name:"joint00"}}},
        { name:"node41", type: "Node", relative: {x: { name:"and4", io: "2/4"}, y: { name:"joint01"}}},
        { name:"joint42", type: "Joint", relative: {x: { name:"and4", io: "3/4"}, y: { name:"jointf2"}}},
        { name:"node43", type: "Node", relative: {x: { name:"and4", io: "4/4"}, y: { name:"joint03"}}},
  
        { name:"node30", type: "Node", relative: {x: { name:"and3", io: "1/4"}, y: { name:"jointf0"}}},
        { name:"node31", type: "Node", relative: {x: { name:"and3", io: "2/4"}, y: { name:"jointf1"}}},
        { name:"node32", type: "Node", relative: {x: { name:"and3", io: "3/4"}, y: { name:"joint02"}}},
        { name:"node33", type: "Node", relative: {x: { name:"and3", io: "4/4"}, y: { name:"joint03"}}},
  
        { name:"node20", type: "Node", relative: {x: { name:"and2", io: "1/4"}, y: { name:"joint00"}}},
        { name:"joint21", type: "Joint", relative: {x: { name:"and2", io: "2/4"}, y: { name:"jointf1"}}},
        { name:"node22", type: "Node", relative: {x: { name:"and2", io: "3/4"}, y: { name:"joint02"}}},
        { name:"node23", type: "Node", relative: {x: { name:"and2", io: "4/4"}, y: { name:"joint03"}}},
  
        { name:"joint10", type: "Joint", relative: {x: { name:"and1", io: "1/4"}, y: { name:"jointf0"}}},
        { name:"node11", type: "Node", relative: {x: { name:"and1", io: "2/4"}, y: { name:"joint01"}}},
        { name:"node12", type: "Node", relative: {x: { name:"and1", io: "3/4"}, y: { name:"joint02"}}},
        { name:"node13", type: "Node", relative: {x: { name:"and1", io: "4/4"}, y: { name:"joint03"}}},
  
        { name:"inv3", type: "Inverter", scale: 0.20, rotate: 90, y: -50, relative: {xy: { name:"node73" }}},
        { name:"inv2", type: "Inverter", scale: 0.20, rotate: 90, relative: {x: { name:"nodeb2"}, y: { name:"inv3"}}},
        { name:"inv1", type: "Inverter", scale: 0.20, rotate: 90, relative: {x: { name:"node91"}, y: { name:"inv3"}}},
        { name:"inv0", type: "Inverter", scale: 0.20, rotate: 90, relative: {x: { name:"node60"}, y: { name:"inv3"}}},
  
        { name:"node3", type: "Node", y:-60, relative: {x: { name:"andE", io: "4/4"}, y: { name:"inv3"}}},
        { name:"node2", type: "Node", y: -20, relative: {x: { name:"andD", io: "3/4"}, y: { name:"inv2"}}},
        { name:"node1", type: "Node", y: -20, relative: {x: { name:"andA", io: "2/4"}, y: { name:"inv1"}}},
        { name:"node0", type: "Node", y: -20, relative: {x: { name:"and5", io: "1/4"}, y: { name:"inv0"}}},
  
        { name:"joint3", type: "Joint", relative: {x: { name:"inv3"}, y: { name:"node3"}}},
        { name:"joint2", type: "Joint", relative: {x: { name:"inv2"}, y: { name:"node2"}}},
        { name:"joint1", type: "Joint", relative: {x: { name:"inv1"}, y: { name:"node1"}}},
        { name:"joint0", type: "Joint", relative: {x: { name:"inv0"}, y: { name:"node0"}}}
    ],
    wires: [
      { points:[{ name:"inv3", io: "out"}, { name:"node73"}]},
      { points:[{ name:"node73"}, { name:"and7", io: "4/4", input: 3}]},
      { points:[{ name:"node73"}, { name:"node63"}]},
      { points:[{ name:"node63"}, { name:"and6", io: "4/4", input: 3}]},
      { points:[{ name:"node63"}, { name:"node53"}]},
      { points:[{ name:"node53"}, { name:"and5", io: "4/4", input: 3}]},
      { points:[{ name:"node53"}, { name:"node43"}]},
      { points:[{ name:"node43"}, { name:"and4", io: "4/4", input: 3}]},
      { points:[{ name:"node43"}, { name:"node33"}]},
      { points:[{ name:"node33"}, { name:"and3", io: "4/4", input: 3}]},
      { points:[{ name:"node33"}, { name:"node23"}]},
      { points:[{ name:"node23"}, { name:"and2", io: "4/4", input: 3}]},
      { points:[{ name:"node23"}, { name:"node13"}]},
      { points:[{ name:"node13"}, { name:"and1", io: "4/4", input: 3}]},
      { points:[{ name:"node13"}, { name:"joint03"}, { name:"and0", io: "4/4", input: 3}]},
  
  
      { points:[{ name:"inv2", io: "out"}, { name:"nodeb2"}]},
      { points:[{ name:"nodeb2"}, { name:"andB", io: "3/4", input: 2}]},
      { points:[{ name:"nodeb2"}, { name:"nodea2"}]},
      { points:[{ name:"nodea2"}, { name:"andA", io: "3/4", input: 2}]},
      { points:[{ name:"nodea2"}, { name:"node92"}]},
      { points:[{ name:"node92"}, { name:"and9", io: "3/4", input: 2}]},
      { points:[{ name:"node92"}, { name:"node82"}]},
      { points:[{ name:"node82"}, { name:"and8", io: "3/4", input: 2}]},
      { points:[{ name:"node82"}, { name:"node32"}]},
      { points:[{ name:"node32"}, { name:"and3", io: "3/4", input: 2}]},
      { points:[{ name:"node32"}, { name:"node22"}]},
      { points:[{ name:"node22"}, { name:"and2", io: "3/4", input: 2}]},
      { points:[{ name:"node22"}, { name:"node12"}]},
      { points:[{ name:"node12"}, { name:"and1", io: "3/4", input: 2}]},
      { points:[{ name:"node12"}, { name:"joint02"}, { name:"and0", io: "3/4", input: 2}]},
  
      { points:[{ name:"inv1", io: "out"}, { name:"node91"}]},
      { points:[{ name:"node91"}, { name:"and9", io: "2/4", input: 1}]},
      { points:[{ name:"node91"}, { name:"nodec1"}]},
      { points:[{ name:"nodec1"}, { name:"andC", io: "2/4", input: 1}]},
      { points:[{ name:"nodec1"}, { name:"jointd1"}, { name:"andD", io: "2/4", input: 1}]},
  
      { points:[{ name:"node91"}, { name:"node81"}]},
      { points:[{ name:"node81"}, { name:"and8", io: "2/4", input: 1}]},
      { points:[{ name:"node81"}, { name:"node51"}]},
      { points:[{ name:"node51"}, { name:"and5", io: "2/4", input: 1}]},
      { points:[{ name:"node51"}, { name:"node41"}]},
      { points:[{ name:"node41"}, { name:"and4", io: "2/4", input: 1}]},
      { points:[{ name:"node41"}, { name:"node11"}]},
      { points:[{ name:"node11"}, { name:"and1", io: "2/4", input: 1}]},
      { points:[{ name:"node11"}, { name:"joint01"}, { name:"and0", io: "2/4", input: 1}]},
  
      { points:[{ name:"inv0", io: "out"}, { name:"node60"}]},
      { points:[{ name:"node60"}, { name:"and6", io: "1/4", input: 0}]},
      { points:[{ name:"node60"}, { name:"node80"}]},
      { points:[{ name:"node80"}, { name:"and8", io: "1/4", input: 0}]},
      { points:[{ name:"node80"}, { name:"nodea0"}]},
      { points:[{ name:"nodea0"}, { name:"andA", io: "1/4", input: 0}]},
      { points:[{ name:"nodea0"}, { name:"nodec0"}]},
      { points:[{ name:"nodec0"}, { name:"andC", io: "1/4", input: 0}]},
      { points:[{ name:"nodec0"}, { name:"jointe0"}, { name:"andE", io: "1/4", input: 0}]},
  
      { points:[{ name:"node60"}, { name:"node40"}]},
      { points:[{ name:"node40"}, { name:"and4", io: "1/4", input: 0}]},
      { points:[{ name:"node40"}, { name:"node20"}]},
      { points:[{ name:"node20"}, { name:"and2", io: "1/4", input: 0}]},
      { points:[{ name:"node20"}, { name:"joint00"}, { name:"and0", io: "1/4", input: 0}]},
  
      { points:[{ name:"node3"}, { name:"joint3"}, { name:"inv3"}]},
      { points:[{ name:"node3"}, { name:"nodee3"}]},
      { points:[{ name:"nodee3"}, { name:"andE", io: "4/4", input: 3}]},
      { points:[{ name:"nodee3"}, { name:"jointf3"}, { name:"andF", io: "4/4", input: 3}]},
      
      { points:[{ name:"nodee3"}, { name:"noded3"}]},
      { points:[{ name:"noded3"}, { name:"andD", io: "4/4", input: 3}]},
      { points:[{ name:"noded3"}, { name:"nodec3"}]},
      { points:[{ name:"nodec3"}, { name:"andC", io: "4/4", input: 3}]},
      { points:[{ name:"nodec3"}, { name:"nodeb3"}]},
      { points:[{ name:"nodeb3"}, { name:"andB", io: "4/4", input: 3}]},
      { points:[{ name:"nodeb3"}, { name:"nodea3"}]},
      { points:[{ name:"nodea3"}, { name:"andA", io: "4/4", input: 3}]},
      { points:[{ name:"nodea3"}, { name:"node93"}]},
      { points:[{ name:"node93"}, { name:"and9", io: "4/4", input: 3}]},
      { points:[{ name:"node93"}, { name:"joint83"}, { name:"and8", io: "4/4", input: 3}]},
  
      { points:[{ name:"node2"}, { name:"joint2"}, { name:"inv2"}]},
      { points:[{ name:"node2"}, { name:"noded2"}]},
      { points:[{ name:"noded2"}, { name:"andD", io: "3/4", input: 2}]},
      { points:[{ name:"noded2"}, { name:"nodee2"}]},
      { points:[{ name:"nodee2"}, { name:"andE", io: "3/4", input: 2}]},
      { points:[{ name:"nodee2"}, { name:"jointf2"}, { name:"andF", io: "3/4", input: 2}]},
      
      { points:[{ name:"noded2"}, { name:"nodec2"}]},
      { points:[{ name:"nodec2"}, { name:"andC", io: "3/4", input: 2}]},
      { points:[{ name:"nodec2"}, { name:"node72"}]},
      { points:[{ name:"node72"}, { name:"and7", io: "3/4", input: 2}]},
      { points:[{ name:"node72"}, { name:"node62"}]},
      { points:[{ name:"node62"}, { name:"and6", io: "3/4", input: 2}]},
      { points:[{ name:"node62"}, { name:"node52"}]},
      { points:[{ name:"node52"}, { name:"and5", io: "3/4", input: 2}]},
      { points:[{ name:"node52"}, { name:"joint42"}, { name:"and4", io: "3/4", input: 2}]},
  
      { points:[{ name:"node1"}, { name:"joint1"}, { name:"inv1"}]},
      { points:[{ name:"node1"}, { name:"nodea1"}]},
      { points:[{ name:"nodea1"}, { name:"andA", io: "2/4", input: 1}]},
      { points:[{ name:"nodea1"}, { name:"nodeb1"}]},
      { points:[{ name:"nodeb1"}, { name:"andB", io: "2/4", input: 1}]},
      { points:[{ name:"nodeb1"}, { name:"nodee1"}]},
      { points:[{ name:"nodee1"}, { name:"andE", io: "2/4", input: 1}]},
      { points:[{ name:"nodee1"}, { name:"jointf1"}, { name:"andF", io: "2/4", input: 1}]},
      
      { points:[{ name:"nodea1"}, { name:"node71"}]},
      { points:[{ name:"node71"}, { name:"and7", io: "2/4", input: 1}]},
      { points:[{ name:"node71"}, { name:"node61"}]},
      { points:[{ name:"node61"}, { name:"and6", io: "2/4", input: 1}]},
      { points:[{ name:"node61"}, { name:"node31"}]},
      { points:[{ name:"node31"}, { name:"and3", io: "2/4", input: 1}]},
      { points:[{ name:"node31"}, { name:"joint21"}, { name:"and2", io: "2/4", input: 1}]},
  
      { points:[{ name:"node0"}, { name:"joint0"}, { name:"inv0"}]},
      { points:[{ name:"node0"}, { name:"node50"}]},
      { points:[{ name:"node50"}, { name:"and5", io: "1/4", input: 0}]},
      { points:[{ name:"node50"}, { name:"node70"}]},
      { points:[{ name:"node70"}, { name:"and7", io: "1/4", input: 0}]},
      { points:[{ name:"node70"}, { name:"node90"}]},
      { points:[{ name:"node90"}, { name:"and9", io: "1/4", input: 0}]},
      { points:[{ name:"node90"}, { name:"nodeb0"}]},
      { points:[{ name:"nodeb0"}, { name:"andB", io: "1/4", input: 0}]},
      { points:[{ name:"nodeb0"}, { name:"noded0"}]},
      { points:[{ name:"noded0"}, { name:"andD", io: "1/4", input: 0}]},
      { points:[{ name:"noded0"}, { name:"jointf0"}, { name:"andF", io: "1/4", input: 0}]},
      
      { points:[{ name:"node50"}, { name:"node30"}]},
      { points:[{ name:"node30"}, { name:"and3", io: "1/4", input: 0}]},
      { points:[{ name:"node30"}, { name:"joint10"}, { name:"and1", io: "1/4", input: 0}]}
    ]
    }
  